export const MOVIES_ON_PAGE_UPDATED = 'MOVIES_ON_PAGE_UPDATED';
export const NUM_OF_MOVIES_PAGE_UPDATED = 'NUM_OF_MOVIES_PAGE_UPDATED';
export const SHOW_MODAL_WINDOW = 'SHOW_MODAL_WINDOW_WITH';
export const CLOSE_MODAL_WINDOW = 'CLOSE_MODAL_WINDOW';