export const MOVIES_ON_PAGE_UPDATED = 'MOVIES_ON_PAGE_UPDATED';
export const MOVIES_LOADING_STARTED = 'MOVIES_LOADING_STARTED';
export const MOVIES_LOADING_SUCCESS = 'MOVIES_LOADING_SUCCESS';
export const MOVIES_LOADING_FAILURE = 'MOVIES_LOADING_FAILURE';

export const NUM_OF_MOVIES_PAGE_UPDATED = 'NUM_OF_MOVIES_PAGE_UPDATED';

export const SET_UP_FAVORITE_LIST = 'SET_UP_FAVORITE_LIST';
export const FAVORITE_MOVIES_UPDATED = 'FAVORITE_MOVIES_UPDATED';
export const MOVIE_ADDED_TO_FAVORITE = 'ADD_MOVIE_TO_FAVORITE';
export const MOVIE_REMOVED_FROM_FAVORITE = 'REMOVE_MOVIE_FROM_FAVORITE';